# Read Excel file 
. import Pandas and Numpy library

In [24]:
import pandas as pd
import numpy as np

df = pd.read_excel("Online Retail (1).xlsx")

# Show fifth record of data set

In [25]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# Shape of dataset
# شکل دیتاست

In [26]:
print(f"Dataset Shape: {df.shape}")
print(f"Number of Rows (Records): {df.shape[0]}")
print(f"Number of Columns (Features): {df.shape[1]}")

Dataset Shape: (541909, 8)
Number of Rows (Records): 541909
Number of Columns (Features): 8

# columns names
# نام ستون ها

In [27]:
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

# columns data type
# نوع داده ی ستون ها

In [28]:
print(df.dtypes)

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

# information of dataset
# اطلاعت دیتاست

In [29]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB
None

# Describe dataseet
# توصیف دیتاست

In [30]:
print(df.describe())

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

# Missing value  and null value of dataset
# مقادیر گم شده و خالی دیتاست

In [31]:
missing_value = df.isna().sum()
print(missing_value)
print("_________________________________")
missing_percent = (
    df.isnull().sum() / len(df) * 100
).round(2)

print(missing_percent)

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
_________________________________
InvoiceNo       0.00
StockCode       0.00
Description     0.27
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     24.93
Country         0.00
dtype: float64

# Duplicated values
# مقادیر تکرای

In [32]:
duplicates = df[df.duplicated()]
print(duplicates)

       InvoiceNo StockCode                        Description  Quantity  \
517       536409     21866        UNION JACK FLAG LUGGAGE TAG         1
527       536409     22866      HAND WARMER SCOTTY DOG DESIGN         1
537       536409     22900    SET 2 TEA TOWELS I LOVE LONDON          1
539       536409     22111       SCOTTIE DOG HOT WATER BOTTLE         1
555       536412     22327  ROUND SNACK BOXES SET OF 4 SKULLS         1
...          ...       ...                                ...       ...
541675    581538     22068        BLACK PIRATE TREASURE CHEST         1
541689    581538     23318     BOX OF 6 MINI VINTAGE CRACKERS         1
541692    581538     22992             REVOLVER WOODEN RULER          1
541699    581538     22694                       WICKER STAR          1
541701    581538     23343       JUMBO BAG VINTAGE CHRISTMAS          1

               InvoiceDate  UnitPrice  CustomerID         Country
517    2010-12-01 11:45:00       1.25     17908.0  United Kingdom
527    2010-12-01 11:45:00       2.10     17908.0  United Kingdom
537    2010-12-01 11:45:00       2.95     17908.0  United Kingdom
539    2010-12-01 11:45:00       4.95     17908.0  United Kingdom
555    2010-12-01 11:49:00       2.95     17920.0  United Kingdom
...                    ...        ...         ...             ...
541675 2011-12-09 11:34:00       0.39     14446.0  United Kingdom
541689 2011-12-09 11:34:00       2.49     14446.0  United Kingdom
541692 2011-12-09 11:34:00       1.95     14446.0  United Kingdom
541699 2011-12-09 11:34:00       2.10     14446.0  United Kingdom
541701 2011-12-09 11:34:00       2.08     14446.0  United Kingdom

[5268 rows x 8 columns]

In [33]:
example_invoice = df["InvoiceNo"].dropna().iloc[0]

invoice_example = df.loc[
    df["InvoiceNo"].eq(example_invoice)
]

display(invoice_example)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom

# Sepereation of feature
# تفکیک ویژگی ها

In [34]:
feature_nature_types = {
    "InvoiceNo":   "Categorical",   
    "StockCode":   "Categorical",   
    "Description": "Categorical",   
    "Quantity":    "Numerical",     
    "InvoiceDate": "Datetime",      
    "UnitPrice":   "Numerical",     
    "CustomerID":  "Categorical",   
    "Country":     "Categorical",  
}

for feature, feature_type in feature_nature_types.items():
    print(f"{feature}:\t{feature_type}")

InvoiceNo:	Categorical
StockCode:	Categorical
Description:	Categorical
Quantity:	Numerical
InvoiceDate:	Datetime
UnitPrice:	Numerical
CustomerID:	Categorical
Country:	Categorical

# Number and pecentage of duplicated values

In [35]:
duplicate_mask = df.duplicated()

duplicate_count = duplicate_mask.sum()

duplicate_percent = duplicate_count / len(df) * 100

print("Duplicate count:", duplicate_count)
print("Duplicate percent:", round(duplicate_percent, 2), "%")

Duplicate count: 5268
Duplicate percent: 0.97 %

# برسی فاکتور های لغو شده
<p>در این دیتا ست فاکتور های که با C شروع میشوند لغو شده هستند.<p>

چند ردیف مربوط به فاکتورهای لغوشده است؟

چند درصد از کل داده‌ها را تشکیل می‌دهند؟

آیا تمام ردیف‌های لغوشده دارای Quantity منفی هستند؟

In [38]:
cancel_mask = df["InvoiceNo"].astype("string").str.startswith("C")

cancelled = df[cancel_mask]

print("Cancelled rows:", len(cancelled))

print("Cancelled percent:", round(
    len(cancelled) / len(df) * 100, 2
), "%")

print("Negative Quantity:", (cancelled["Quantity"] < 0).sum())

print("Non-negative Quantity:", (cancelled["Quantity"] >= 0).sum())

Cancelled rows: 9288
Cancelled percent: 1.71 %
Negative Quantity: 9288
Non-negative Quantity: 0

# برسی قیمت های صفر و منفی

In [39]:
zero_price = df[df["UnitPrice"] == 0]

negative_price = df[df["UnitPrice"] < 0]

print("Zero prices:", len(zero_price))
print("Negative prices:", len(negative_price))

display(zero_price.head(10))
display(negative_price.head(10))

Zero prices: 2515
Negative prices: 2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

# برسی مقادیر گم شده در Costumer id

In [43]:
missing_customer = df[df["CustomerID"].isna()]

print("Missing CustomerID:", len(missing_customer))

print(
    missing_customer["Country"]
    .value_counts()
)

display(missing_customer.head(20))

Missing CustomerID: 135080
Country
United Kingdom    133600
EIRE                 711
Hong Kong            288
Unspecified          202
Switzerland          125
France                66
Israel                47
Portugal              39
Bahrain                2
Name: count, dtype: int64

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1452,536544,21809,CHRISTMAS HANGING TREE WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1453,536544,21810,CHRISTMAS HANGING STAR WITH BELL,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1454,536544,21811,CHRISTMAS HANGING HEART WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1455,536544,21821,GLITTER STAR GARLAND WITH BELLS,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1456,536544,21822,GLITTER CHRISTMAS TREE WITH BELLS,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1457,536544,21823,PAINTED METAL HEART WITH HOLLY BELL,2,2010-12-01 14:32:00,2.98,NaN,United Kingdom
1458,536544,21844,RED RETROSPOT MUG,2,2010-12-01 14:32:00,5.91,NaN,United Kingdom
1459,536544,21851,LILAC DIAMANTE PEN IN GIFT BOX,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1460,536544,21870,I CAN ONLY PLEASE ONE PERSON MUG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1461,536544,21871,SAVE THE PLANET MUG,5,2010-12-01 14:32:00,3.36,NaN,United Kingdom

# برسی مقادیر گم شده در Description

In [44]:
missing_description = df[df["Description"].isna()]

print("Missing Description:", len(missing_description))

print(
    "Missing CustomerID among them:",
    missing_description["CustomerID"].isna().sum()
)

print(
    "Zero UnitPrice among them:",
    (missing_description["UnitPrice"] == 0).sum()
)

print(
    "Negative UnitPrice among them:",
    (missing_description["UnitPrice"] < 0).sum()
)

display(missing_description.head(20))

Missing Description: 1454
Missing CustomerID among them: 1454
Zero UnitPrice among them: 1454
Negative UnitPrice among them: 0

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom

# شمارش مقادیر یکتا
در این بخش تعداد مشتریان، فاکتورها، محصولات و کشورها را محاسبه می‌کنیم

هدف چیست؟

ابعاد واقعی دیتاست را بهتر بشناسیم.

برای مثال، ۵۴۱ هزار ردیف به معنی ۵۴۱ هزار مشتری نیست؛ ممکن است یک مشتری در چندین فاکتور و هر فاکتور شامل چندین ردیف کالا باشد.

همچنین تعداد کدهای متمایز لزوماً برابر تعداد محصولات واقعی نیست

In [45]:
print("Unique customers:", df["CustomerID"].nunique())

print("Unique invoices:", df["InvoiceNo"].nunique())

print("Unique products/codes:", df["StockCode"].nunique())

print("Unique countries:", df["Country"].nunique())

Unique customers: 4372
Unique invoices: 25900
Unique products/codes: 4070
Unique countries: 38